package com.magmaguy.betterstructures.modules;

import com.magmaguy.betterstructures.config.modulegenerators.ModuleGeneratorsConfigFields;
import com.magmaguy.betterstructures.thirdparty.WorldGuard;
import org.bukkit.Location;
import org.bukkit.World;

/**
 * Preflight/final guard for naturally generated modular dungeons.
 *
 * <p>The triggering chunk is already generated by the time ChunkLoadEvent is
 * delivered, so it is the one generated chunk allowed inside the footprint.
 * Every other footprint chunk must still be untouched. WorldGuard is checked
 * as one cuboid so a dungeon cannot start outside a region and extend into it.</p>
 */
public final class DungeonFootprintGuard {
    private DungeonFootprintGuard() {
    }

    public record Footprint(int minX, int minZ, int maxX, int maxZ) {
        int minChunkX() {
            return Math.floorDiv(minX, 16);
        }

        int minChunkZ() {
            return Math.floorDiv(minZ, 16);
        }

        int maxChunkX() {
            return Math.floorDiv(maxX, 16);
        }

        int maxChunkZ() {
            return Math.floorDiv(maxZ, 16);
        }
    }

    public static Footprint calculate(Location startLocation,
                                      ModuleGeneratorsConfigFields fields) {
        int nodeSize = fields.getModuleSizeXZ();
        int interiorRadius = Math.max(0, fields.getRadius() - 1);

        // WFCLattice.latticeToWorld() places lattice x/z origins half a node
        // behind the logical center. Only the interior [-r+1, r-1] nodes can
        // contain modules; the +/-r planes are boundary "nothing" nodes.
        int minX = startLocation.getBlockX()
                - interiorRadius * nodeSize
                - nodeSize / 2;
        int minZ = startLocation.getBlockZ()
                - interiorRadius * nodeSize
                - nodeSize / 2;
        int maxX = startLocation.getBlockX()
                + interiorRadius * nodeSize
                - nodeSize / 2
                + nodeSize - 1;
        int maxZ = startLocation.getBlockZ()
                + interiorRadius * nodeSize
                - nodeSize / 2
                + nodeSize - 1;
        return new Footprint(minX, minZ, maxX, maxZ);
    }

    public static boolean isClear(World world,
                                  Location startLocation,
                                  ModuleGeneratorsConfigFields fields,
                                  int triggeringChunkX,
                                  int triggeringChunkZ) {
        if (world == null || startLocation == null || fields == null) return false;
        Footprint footprint = calculate(startLocation, fields);

        for (int chunkX = footprint.minChunkX(); chunkX <= footprint.maxChunkX(); chunkX++) {
            for (int chunkZ = footprint.minChunkZ(); chunkZ <= footprint.maxChunkZ(); chunkZ++) {
                if (chunkX == triggeringChunkX && chunkZ == triggeringChunkZ) continue;
                // World#isChunkGenerated does not load the chunk. This keeps the
                // safety check from causing the generation it is trying to avoid.
                if (world.isChunkGenerated(chunkX, chunkZ)) return false;
            }
        }

        return !WorldGuard.overlapsAnyRegion(
                world,
                footprint.minX(), world.getMinHeight(), footprint.minZ(),
                footprint.maxX(), world.getMaxHeight() - 1, footprint.maxZ());
    }
}
